packages:
  - "packages/*"
  - "apps/*"
  - "scripts"
  - "docs"

overrides:
  "form-data": "4.0.6"
  "js-yaml@4": "5.2.2"

allowBuilds:
  '@prisma/engines': false
  better-sqlite3: true
  esbuild: true
  prisma: false
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.9.15'
  - '@turbo/darwin-arm64@2.9.15'
  - '@turbo/linux-64@2.9.15'
  - '@turbo/linux-arm64@2.9.15'
  - '@turbo/windows-64@2.9.15'
  - '@turbo/windows-arm64@2.9.15'
  - turbo@2.9.15
  - better-auth@1.6.19
  - '@better-auth/core@1.6.19'
  - '@better-auth/drizzle-adapter@1.6.19'
  - '@better-auth/kysely-adapter@1.6.19'
  - '@better-auth/memory-adapter@1.6.19'
  - '@better-auth/mongo-adapter@1.6.19'
  - '@better-auth/prisma-adapter@1.6.19'
  - '@better-auth/telemetry@1.6.19'
  - '@inertiajs/core@3.6.1'
  - '@inertiajs/react@3.6.1'
  - '@typescript-eslint/eslint-plugin'
  - '@typescript-eslint/parser'
  - '@typescript-eslint/project-service'
  - '@typescript-eslint/scope-manager'
  - '@typescript-eslint/tsconfig-utils'
  - '@typescript-eslint/type-utils'
  - '@typescript-eslint/types'
  - '@typescript-eslint/typescript-estree'
  - '@typescript-eslint/utils'
  - '@typescript-eslint/visitor-keys'
  - typescript-eslint
  - '@vitest/coverage-v8'
  - '@vitest/expect'
  - '@vitest/mocker'
  - '@vitest/pretty-format'
  - '@vitest/runner'
  - '@vitest/snapshot'
  - '@vitest/spy'
  - '@vitest/utils'
  - vitest